export default {
  'txt': 'icon/file.svg', // default
  '.': 'icon/folder.svg', // folder
  'pdf': 'icon/acrobat.svg',
  'c': 'icon/c.svg',
  'cpp': 'icon/c.svg',
  'h': 'icon/c.svg',
  'css': 'icon/css.svg',
  'xls': 'icon/excel.svg',
  'xlsx': 'icon/excel.svg',
  'csv': 'icon/excel.svg',
  'html': 'icon/html.svg',
  'htm': 'icon/html.svg',
  'jpeg': 'icon/image.png',
  'jpg': 'icon/image.png',
  'png': 'icon/image.png',
  'gif': 'icon/image.png',
  'tif': 'icon/image.png',
  'tiff': 'icon/image.png',
  'svg': 'icon/image.png',
  'js': 'icon/js.svg',
  'mp3': 'icon/music.png',
  'aac': 'icon/music.png',
  'wav': 'icon/music.png',
  'ppt': 'icon/ppt.svg',
  'pptx': 'icon/ppt.svg',
  'py': 'icon/python.svg',
  'doc': 'icon/word.svg',
  'docx': 'icon/word.svg',
  'mp4': 'icon/youtube.svg',
  'mov': 'icon/youtube.svg',
  'avi': 'icon/youtube.svg',
  'flv': 'icon/youtube.svg',
  'webm': 'icon/youtube.svg',
  'zip': 'icon/zip.svg',
  'rar': 'icon/zip.svg',
  '7z': 'icon/zip.svg',
  'gz': 'icon/zip.svg'
}